### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc when training

### ISSUE THREAD

**Issue by RoyDrew** [kcheng1021/UC-NeRF#3]
Nice Work! I met this bug when using the train_waymo.sh.

**terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc**

I have followed the instruction to train and also installed gridencoder. 
My torch version is 1.12.0+cu113.
I wonder if it is revelant to the cuda extension in the setup (pip install ./extensions/cuda) that isn't provided yet. Do you have any ideas solving this bug? Thanks a lot!

```
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
Loading model from: /DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
Loading model from: /DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
Loading model from: /DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
Loading model from: /DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
Loading model from: /DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
Loading model from: /DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
Loading model from: /DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 2961871) of binary: /DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/bin/python
Traceback (most recent call last):
  File "/DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1008, in launch_command
    multi_gpu_launcher(args)
  File "/DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/accelerate/commands/launch.py", line 666, in multi_gpu_launcher
    distrib_run.run(args)
  File "/DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/DATA_EDS2/yebj/yebj2304/miniconda3/envs/ucnerf/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=========================================================
train.py FAILED
---------------------------------------------------------
Failures:
[1]:
  time      : 2023-12-20_16:01:25
  host      : lthpc-2.local
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 2961872)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 2961872
```

**Comment by kcheng1021** [comment]
Fix it by modifying the environment setup. Please check it.
